### ISSUE TITLE
NoEnabledDecoderFound

### ISSUE THREAD

**Issue by edmacdonald** [imazen/imageflow-dotnet-server#31]
Hi Lilith,

I'm getting quite a few of these exceptions, all with the same `[3C, 21, 44, 4F, 43, 54, 59, 50, 45, 20, 68, 74]` string of numbers.  Any suggestions on how I might troubleshoot this?

All of the ones I've looked at so far have been facebook profile images in case you've run into that before.  I was trying to figure out what disk cache folder it would be in so I could examine it.  From the stack trace it looks like it successfully downloaded something, and was trying to read it for processing.  

Thanks
-Ed

```
Imageflow.Bindings.ImageflowException: ImageMalformed: NoEnabledDecoderFound: No ENABLED decoder found for file starting in [3C, 21, 44, 4F, 43, 54, 59, 50, 45, 20, 68, 74] at
imageflow_core\src\codecs\mod.rs:155:20
https://github.com/imazen/imageflow/blob/e8992576089a3d0e5e0a9a4f3b7f39d5aec291c9/imageflow_core\src\codecs\mod.rs#L155
imageflow_core\src\context.rs:194:103
https://github.com/imazen/imageflow/blob/e8992576089a3d0e5e0a9a4f3b7f39d5aec291c9/imageflow_core\src\context.rs#L194
imageflow_core\src\context.rs:235:66
https://github.com/imazen/imageflow/blob/e8992576089a3d0e5e0a9a4f3b7f39d5aec291c9/imageflow_core\src\context.rs#L235
imageflow_abi\src\lib.rs:703:62
https://github.com/imazen/imageflow/blob/e8992576089a3d0e5e0a9a4f3b7f39d5aec291c9/imageflow_abi\src\lib.rs#L703


   at Imageflow.Bindings.JobContext.AssertReady()
   at Imageflow.Bindings.JobContext.AddInputBytesPinned(Int32 ioId, Byte[] buffer, Int64 offset, Int64 count)
   at Imageflow.Bindings.JobContext.AddInputBytesPinned(Int32 ioId, ArraySegment`1 buffer)
   at Imageflow.Fluent.ImageJob.FinishAsync(JobExecutionOptions executionOptions, SecurityOptions securityOptions, CancellationToken cancellationToken)
   at Imageflow.Server.ImageJobInfo.ProcessUncached()
   at Imageflow.Server.ImageflowMiddleware.<>c__DisplayClass17_0.<<ProcessWithDiskCache>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Imazen.DiskCache.AsyncCustomDiskCache.<>c__DisplayClass27_0.<<GetCachedFile>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Imazen.DiskCache.AsyncLockProvider.TryExecuteAsync(String key, Int32 timeoutMs, AsyncLockCallback success)
   at Imazen.DiskCache.AsyncCustomDiskCache.GetCachedFile(String keyBasis, String extension, AsyncWriteResult writeCallback, Int32 timeoutMs, Boolean asynchronous)
   at Imazen.DiskCache.ClassicDiskCache.GetOrCreate(String key, String fileExtension, AsyncWriteResult writeCallback)
   at Imageflow.Server.ImageflowMiddleware.ProcessWithDiskCache(HttpContext context, String cacheKey, ImageJobInfo info)
   at Imageflow.Server.ImageflowMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()
```

**Comment by edmacdonald** [comment]
That string of hex characters converted to ascii is `<!DOCTYPE ht` so the underlying issue is definitely not ImageFlow.
